baseURL: "https://fgoncalves.dev" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Filipe Gonçalves
paginate: 6
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-8PP3GHQ1CW

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
      languageName: "English"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
      menu:
        main:
          - name: Home
            url: /
            weight: 5
          - name: Archive
            url: archives
            weight: 10
          - name: Search
            url: search/
            weight: 15
          - name: Tags
            url: tags/
            weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: local # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Filipe Gonçalves - https://filipe07.github.io/personal-page/"
    author: Filipe Gonçalves

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    comments: false
    images: ["papermod-cover.png", "me.png"]

    homeInfoParams:
        Title: "Hi there"
        TitleImage: "me.png"
        Content: >
            Welcome to my personal page.

            - I am **Filipe Gonçalves**, an Engineering Manager at Infraspeak. This page will explore topics about team management, agile methodologies, and software engineering fueled by Padel sport.

    socialIcons:
        - name: medium
          url: "https://medium.com/@filipe07"
        - name: linkedin
          url: "https://www.linkedin.com/in/filipe07/"
        - name: Rss
          url: "index.xml"
        - name: KoFi
          url: "https://ko-fi.com/filipegoncalves"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

services:
    instagram:
        disableInlineCSS: false
    twitter:
        disableInlineCSS: false
